/// SUGO – Scan & Update, Groceries Organizer.
///
/// Initialises Firebase, applies the wabi-sabi earth theme, and provides
/// a custom navigation shell with a floating action button for scanning.
library;

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'inventory_page.dart';
import 'scanner_page.dart';
import 'theme.dart';

Future<void> main() async {
  // Ensure Flutter bindings are ready before calling async code.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase with the platform-specific config.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const FoodInventoryApp());
}

/// Root widget – sets up the SUGO earth theme.
class FoodInventoryApp extends StatelessWidget {
  const FoodInventoryApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SUGO',
      debugShowCheckedModeBanner: false,
      theme: sugoTheme(),
      home: const HomePage(),
    );
  }
}

/// Shell page with bottom navigation and a centred FAB for scanning.
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _currentIndex = 0;

  /// The main pages.
  final _pages = const <Widget>[InventoryPage(), ScannerPage()];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(index: _currentIndex, children: _pages),

      // ── Floating scan button ──
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => _currentIndex = 1),
        tooltip: 'Scan barcode',
        child: const Icon(Icons.qr_code_scanner_rounded, size: 28),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,

      // ── Bottom navigation ──
      bottomNavigationBar: BottomAppBar(
        shape: const CircularNotchedRectangle(),
        notchMargin: 8,
        color: Colors.white,
        elevation: 8,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            // Inventory tab
            _NavItem(
              icon: Icons.inventory_2_outlined,
              selectedIcon: Icons.inventory_2,
              label: 'Inventory',
              isSelected: _currentIndex == 0,
              onTap: () => setState(() => _currentIndex = 0),
            ),
            const SizedBox(width: 48), // Space for FAB
            // Scan tab
            _NavItem(
              icon: Icons.history_outlined,
              selectedIcon: Icons.history,
              label: 'Scanner',
              isSelected: _currentIndex == 1,
              onTap: () => setState(() => _currentIndex = 1),
            ),
          ],
        ),
      ),
    );
  }
}

/// A single navigation item in the bottom bar.
class _NavItem extends StatelessWidget {
  final IconData icon;
  final IconData selectedIcon;
  final String label;
  final bool isSelected;
  final VoidCallback onTap;

  const _NavItem({
    required this.icon,
    required this.selectedIcon,
    required this.label,
    required this.isSelected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final color = isSelected ? SugoColors.moss : SugoColors.warmGrey;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 6),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(isSelected ? selectedIcon : icon, color: color, size: 22),
            const SizedBox(height: 1),
            Text(
              label,
              style: TextStyle(
                fontSize: 10,
                fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
                color: color,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
