/// Food Inventory – main entry point.
///
/// Initialises Firebase, sets up theming, and provides a bottom-navigation
/// shell with two tabs: Inventory and Scanner.
library;

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'inventory_page.dart';
import 'scanner_page.dart';

Future<void> main() async {
  // Ensure Flutter bindings are ready before calling async code.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase with the platform-specific config.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const FoodInventoryApp());
}

/// Root widget – sets up Material 3 theming and navigation.
class FoodInventoryApp extends StatelessWidget {
  const FoodInventoryApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Food Inventory',
      debugShowCheckedModeBanner: false,

      // ── Light theme ──
      theme: ThemeData(
        colorSchemeSeed: Colors.teal,
        useMaterial3: true,
        brightness: Brightness.light,
      ),

      // ── Dark theme ──
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.teal,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      themeMode: ThemeMode.system,

      home: const HomePage(),
    );
  }
}

/// Shell page with a bottom navigation bar.
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _currentIndex = 0;

  /// The two main pages.
  final _pages = const <Widget>[InventoryPage(), ScannerPage()];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // IndexedStack preserves state when switching tabs.
      body: IndexedStack(index: _currentIndex, children: _pages),
      bottomNavigationBar: NavigationBar(
        selectedIndex: _currentIndex,
        onDestinationSelected: (i) => setState(() => _currentIndex = i),
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.inventory_2_outlined),
            selectedIcon: Icon(Icons.inventory_2),
            label: 'Inventory',
          ),
          NavigationDestination(
            icon: Icon(Icons.qr_code_scanner_outlined),
            selectedIcon: Icon(Icons.qr_code_scanner),
            label: 'Scan',
          ),
        ],
      ),
    );
  }
}
